### ISSUE TITLE
codeship_aws_eb_deploy includes .git directory

### ISSUE THREAD

**Issue by flashbackzoo** [codeship-library/aws-utilities#30]
Seems the git directory is being included in the zip

![screen shot 2016-11-25 at 11 45 52 am](https://cloud.githubusercontent.com/assets/878176/20610888/8db0b78c-b305-11e6-82ff-9cf416377305.png)

I think [this line](https://github.com/codeship-library/aws-utilities/blob/master/deployment/scripts/codeship_aws_eb_deploy#L21) needs to be changed to:

`zip -x */.git* -x *.git* -x *.hg* -r "$DEPLOYMENT_FILE_NAME" ./`

Taking that a step further - what are your thoughts on using `git-archive` instead of `zip` for this?

It would make it possible to exclude local volumes and other files from the archive via `.gitattributes`

**Comment by devinus** [comment]
I can confirm this issue.

**Comment by flashbackzoo** [comment]
PR: https://github.com/codeship-library/aws-utilities/pull/33

**Comment by devinus** [comment]
Using `git-archive` would be ideal.

**Comment by andyshinn** [comment]
I don't think `git-archive` would work in all cases. For example, I am running `composer` commands to populate the `vendor` folder before deployment. I don't store this data in git so it wouldn't be included in `git-archive`.

**Comment by AaronTorgerson** [comment]
Frustrating to see PR #33 sitting so long without any motion. 

In any case, I found a workaround for this problem using volumes:

```
awsdeployment:
    image: codeship/aws-deployment
    encrypted_env_file: codeship-env.encrypted
    environment:
    - AWS_DEFAULT_REGION=us-east-1
    volumes:
    - ./:/deploy
    - /deploy/.git
    - /deploy/.venv
    - /deploy/.idea
    - /deploy/.local-cache
```

Creating a volume over the problematic dirs in the source tree will result in the files in those dirs from being visible to the container. 

Cheers & good luck! 🍻
